from src.tasks.classification import train_supervised_classifier, train_linear_classifier
from src.tasks.retrieval import run_mfcc_retrieval, run_ml_retrieval
from src.tasks.llm_baseline import evaluate_llm_predictions
